### ISSUE TITLE
Cleanup pasar

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-client#10]

**Comment by towardthesea** [comment]
Check [it](https://github.com/robotology/icub-client/commit/3808adfc6758480b5f2ee5d771d762de4d81ae23) @Tobias-Fischer  :smile:

**Comment by Tobias-Fischer** [comment]
Great! I did some more cleaning here: https://github.com/robotology/icub-client/commit/5e688109f3f40d83712988e6be11f89ba18e951b

Could you add the doc on the `handlerPort` to `pasar.xml`? Then we can close :)

**Comment by Tobias-Fischer** [comment]
PS: This was the last unassigned issue - great :+1:

**Comment by towardthesea** [comment]
I will finish tomorrow :D

**Comment by towardthesea** [comment]
Hope [it](https://github.com/robotology/icub-client/commit/7959c6d3920f4f77e953eb279a1709baa5011464) works fine :smiley:

**Comment by Tobias-Fischer** [comment]
Great! Well done. Did some more small changes, guess that's more than good enough now :)

**Comment by towardthesea** [comment]
The changes are not so small :smiley: :+1:
