### ISSUE TITLE
Cleanup iol2opc

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-client#14]
Code looks good, mostly needs documentation

**Comment by towardthesea** [comment]
I have just updated! Please have a look @Tobias-Fischer !

**Comment by Tobias-Fischer** [comment]
Great, thanks a lot! All good, I just did some [minor changes](https://github.com/robotology/icub-client/commit/5bf0c142b154b0ac4115107d8627f6da45c66b36)
