### ISSUE TITLE
Cleanup SAM

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-client#17]

**Comment by Tobias-Fischer** [comment]
Ping @dcam0050

**Comment by dcam0050** [comment]
Hey @Tobias-Fischer I've submitted my first iteration for the documentation. What do you think?

**Comment by Tobias-Fischer** [comment]
I've had a quick look, and it looks good! Will have a closer look in the next couple of days.
One comment: I've seen that you put `/src/modules/SAM/SAM_Tests` in the `.gitignore`, but you did not delete the folder itself. I am not sure whether `SAM_Tests` should still be part of the repo. If not, please delete the folder. If it should be, I am not sure why it should be part of the `.gitignore`.

**Comment by dcam0050** [comment]
Yes you're right forgot to delete the whole folder. Will do it tomorrow.

**Comment by Tobias-Fischer** [comment]
Cool, nice.
A few more questions: there is a `CMakeLists.txt` in `SAM_Core` which copies some of the Python scripts to the install directory. Are the other files not needed in the install dir? Also, none of the drivers are copied (there is no `CMakeLists.txt` in that folder) - is that right?

**Comment by Tobias-Fischer** [comment]
Hi,
The documentation itself all looks good! However, `SAM Drivers` shows up separately within the modules (https://robotology.github.io/icub-client/doxygen/doc/html/group__icubclient__modules.html). I am not sure why that is - could you please have a look?
Think we can close this soon - just this little issue and the question regarding the `CMakeLists.txt` remains open.
PS: The documentation now updates automatically as soon as you push something to the `master` branch. Travis takes care of it,

**Comment by dcam0050** [comment]
Yes that is correct, only samSupervisor, trainSAMModel, interactionSAMModel and samOptimiser are needed in the install path because those are called using system calls, the rest are found via pythonpath

**Comment by dcam0050** [comment]
In the case of icub client, adding modules directory to the pythonpath

**Comment by Tobias-Fischer** [comment]
Alright, sounds reasonable :-). 
Some small things:
1. Could you please add this requirement (adding `SAM` to `PYTHONPATH` to https://github.com/robotology/icub-client/blob/master/src/modules/SAM/README.md?
2. Also, there are some blanks (______) - could you please fill them? 
3. And last but not least, we need a tutorial how to train the face recognition module; could you add this to https://github.com/robotology/icub-client/tree/master/src/doc? I remember there is some weird stuff with a path which needs to be added when calling `CLMYarp`; this should be documented as well.

Thanks a lot!
Best, Tobi

**Comment by dcam0050** [comment]
Which blanks are you referring to?

**Comment by Tobias-Fischer** [comment]
Important notes: "You can get an example <FolderName> from ______ which contains data, config.ini and pre-trained models for ______"

**Comment by dcam0050** [comment]
Ahh OK!

**Comment by dcam0050** [comment]
Added a face recognition training tutorial with e8e2dde.

**Comment by Tobias-Fischer** [comment]
Nice! I'll close once the documentation is updated through Travis and it all looks okay :)

**Comment by Tobias-Fischer** [comment]
Did some minor fix, all good. Thanks a lot!
