### ISSUE TITLE
Documentation actionRecogDataDumper

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-client#18]
Code looks good, mostly needs documentation

**Comment by Tobias-Fischer** [comment]
Ping @dcam0050

**Comment by dcam0050** [comment]
Hey Toby, I'm trying to get actionRecogDataDumper to show up in the compiled documentation but it's not being detected. I have put 
```/**
 * \ingroup actionRecogDataDumper
 */ 
```

 in `main.cpp` and copied `guiUpdater.xml` to the `actionRecogDataDumper` folder and changed 

`<name>guiUpdater</name>` to `<name>actionRecogDataDumper</name>`. I can't see it in the modules list though.

**Comment by Tobias-Fischer** [comment]
Hey Daniel, seeing that you're on holiday, don't worry about it not showing up. I can take care of that. Just commit whatever you have documented so far, and I'll fix the bugs ;)

**Comment by dcam0050** [comment]
Great! I'll do that

**Comment by Tobias-Fischer** [comment]
And don't forget to push :P

**Comment by Tobias-Fischer** [comment]
Thanks @dcam0050, closing here :)
