### ISSUE TITLE
Cleanup touchDetector

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-client#21]
Code looks good, mostly needs documentation

**Comment by towardthesea** [comment]
Let me check it then!

**Comment by towardthesea** [comment]
Hi @Tobias-Fischer 
Please check these:
[push 1](https://github.com/robotology/icub-client/commit/ab7511ff30cba409a82a56b863295557001e2dc7)
[push 2](https://github.com/robotology/icub-client/commit/c3f87ce419e09b9fe8a06bab069908da0cf1cdcf)
[push 3](https://github.com/robotology/icub-client/commit/27ceb17a4f9e2e9d87a3c5e318f427d75efd07aa)

Then we can close this!

**Comment by Tobias-Fischer** [comment]
Thanks a lot! All looks fine, did some tiny changes in https://github.com/robotology/icub-client/commit/0e036e268495664f893798da3aa5f73de723a755 - we can close this. Thanks :)
