### ISSUE TITLE
Karma clarification

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-client#25]
Hi @towardthesea,
I'm not sure whether we should use `Karma` or `KarmaWYSIWYD` (seeing that all the reactive control stuff is not needed in `icub-client`). Could you please advice on that? Please add the dependency in the `README.md` accordingly.

Thanks, Tobi

**Comment by Tobias-Fischer** [comment]
Hey @towardthesea,
Sorry to be annoying, but I think we need to dig a little deeper.
In `ICubClient`, there are two overloaded methods of `pushKarmaLeft` etc., e.g. 
```
bool pushKarmaLeft(const std::string &objName, const double &targetPosYLeft,
    const std::string &armType = "selectable",
    const yarp::os::Bottle &options = yarp::os::Bottle());
``` 
and 
```
bool pushKarmaLeft(const std::string &objName, const yarp::sig::Vector &objCenter, const double &targetPosYLeft,
    const std::string &armType = "selectable",
    const yarp::os::Bottle &options = yarp::os::Bottle());
```
As the end user will need to provide the `objName` anyways (for the `iolReachingCalibration`), I think we should get rid of the second overloaded method(s) (i.e. the one with `objName` and `objCenter`). Could you do that?

Thanks a lot,
Tobi

**Comment by towardthesea** [comment]
I am checking it right now!

**Comment by towardthesea** [comment]
Hi @Tobias-Fischer ,
The same thing also happen to other `pushKarma` and `pullKarma`. Actually, they were designed as the first one is a wrapper of the 2nd one (with `objName` and `objCenter`). There are 2 options for this case:
- Turn 2nd one to private --> simpler
- Remove 2nd one and adapt the 1st one

Tell me which option you prefer?
Cheers,
Phuong

**Comment by Tobias-Fischer** [comment]
Hey @towardthesea,
I think we should remove the 2nd one and adapt the 1st one. I think it should still be quite easy :).

Best, Tobi
