### ISSUE TITLE
Use superquadrics to extract the sizes of objects to be shown in iCubGui

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-client#32]
@towardthesea please consider extending the `iol2opc` to display objects within the iCubGui along with the correct sizes retrieved using vision.

To this end, the idea is to use [**superquadric-model**](https://github.com/robotology/superquadric-model) developed by @giuliavezzani.

**Comment by towardthesea** [comment]
This [PR](https://github.com/robotology/icub-client/pull/40) to solve the issue!

**Comment by Tobias-Fischer** [comment]
Thanks @towardthesea :+1:
