### ISSUE TITLE
Setup new documentation

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-client#4]

**Comment by towardthesea** [comment]
@Tobias-Fischer Do we have the format for **service** part in `xml` file? The `iol2opc` module needs it.

Thanks!

**Comment by Tobias-Fischer** [comment]
Yes :). You can use all the features described [here](http://wiki.icub.org/brain/xml_module_documentation.html) @towardthesea  :)

**Comment by towardthesea** [comment]
I thought we have something special :smiling_imp:

**Comment by Tobias-Fischer** [comment]
Closing here, tracking the rest in the individual issues.
