### ISSUE TITLE
SAM subsystem

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-client#6]
To be created

**Comment by dcam0050** [comment]
First working version with e81b7b0. More functions to follow.

**Comment by Tobias-Fischer** [comment]
Looks good. As far as I am concerned, we only need to implement the following methods in the subsystem:
- `ask_face_label` (then to be used in proactiveTagging.cpp; and all other references to SAM should be removed, you can basically copy and paste lines 234-240; also please make the return value consistent to be "nack" if the subsystem is not available / the face is not being recognised)
- `ask_action_label` (then to be used in recognitionOrder.cpp); same as before you can copy and paste lines 40-48).
Thanks a lot :)

**Comment by dcam0050** [comment]
In proactiveTagging.cpp lines 67-74 I'm guessing I need to replace those with icubclient logic now yes?

**Comment by dcam0050** [comment]
Ok I got it you just need to add SAM to ini file and iCub->connect connects all subsystems

**Comment by Tobias-Fischer** [comment]
Regarding the replacement: Yes, just replace with `iCub->getSAMClient()->getFaceLabel()` :+1:

**Comment by dcam0050** [comment]
Ok the last commit updated recognitionOrder and the one before it proactiveTagging with the new subsystem.

**Comment by dcam0050** [comment]
I've opted for a more general approach using askXLabel(face) for proactiveTagging and askXLabel(action) for recognitionOrder

**Comment by Tobias-Fischer** [comment]
Hey @dcam0050,
looks good, thanks! Check this out - https://github.com/robotology/icub-client/commit/eb5c12bc41d2d7727466bae54f605f83a7a9461e - in C++11 you can return tuples ;). Think it makes more sense that way.
I guess we can close this.

Thanks, Tobi

**Comment by dcam0050** [comment]
cool!
