### ISSUE TITLE
Documentation on how to create new subsystem

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-client#7]
Can be done alongside #6

**Comment by Tobias-Fischer** [comment]
Please add to https://robotology.github.io/icub-client/doxygen/doc/html/group__icubclient__tutorials.html @dcam0050

**Comment by dcam0050** [comment]
Should be done with e81b7b0

**Comment by Tobias-Fischer** [comment]
Looking good, thanks a lot :)
