### ISSUE TITLE
Cleanup agentDetector

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-client#8]

**Comment by towardthesea** [comment]
I will do it!
Cheers.

**Comment by towardthesea** [comment]
Check [it](https://github.com/robotology/icub-client/commit/11428e428c5a585a3dd31ba2723b5369d0393b43) @Tobias-Fischer 

Cheers :smile:

**Comment by Tobias-Fischer** [comment]
Hi @towardthesea, you're fast, great :). All looks good - just one thing, could you replace `cout` / `cerr` with `yInfo`, `yWarning` etc.? Then we can close this :+1: 
Also see https://github.com/robotology/icub-client/commit/1bf76917e3500a421d96f79b5c5f9a4c5fedfc5c

**Comment by towardthesea** [comment]
Check [it](https://github.com/robotology/icub-client/commit/83ebf0aafd4ecdd7eae23b680875c8530f94e587) @Tobias-Fischer :smile:

**Comment by Tobias-Fischer** [comment]
Thanks a lot!

**Comment by Tobias-Fischer** [comment]
Hey @towardthesea, I just noticed that the port descriptions in the `agentDetector.xml` need updating. The ones which are in the XML are not there anymore, but others which stream images are missing. Could you add these ports to the XML?

Thanks a lot, Tobi

**Comment by Tobias-Fischer** [comment]
Ping @towardthesea :)

**Comment by towardthesea** [comment]
I will do it tomorrow @Tobias-Fischer :)

**Comment by towardthesea** [comment]
Check [it](https://github.com/robotology/icub-client/commit/7af959bba6e569beab52264f20512930b8320bde) @Tobias-Fischer

**Comment by Tobias-Fischer** [comment]
Thanks :+1:
